config/routes.rb
Rails.application.routes.draw do
  resources :cities, only: %w[new index show create destroy]
  devise_for :users
  root 'cities#all_cities'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :user

  def current_weather_obj 
    return @current_weather_json if @current_weather_json
    api = ENV['OPEN_WEATHER_MAP_API_KEY']
    response = Faraday.get "http://api.openweathermap.org/data/2.5/weather?q=#{name}&appid=#{api}&units=imperial"
    @current_weather_json = JSON::parse(response.body)
  end

  def current_forecast_obj 
    return @current_forecast_json if @current_forecast_json
    api = ENV['OPEN_WEATHER_MAP_API_KEY']
    response = Faraday.get "http://api.openweathermap.org/data/2.5/forecast?q=#{name}&appid=#{api}&units=imperial"
    @current_forecast_json = JSON::parse(response.body)
  end

  def current_temp
    current_weather_obj["main"]
  end  
  def current_weather
    current_weather_obj["weather"][0]
  end

  def filtered_five_day_forecast_list
    current_forecast_obj['list'].select{ |obj| midnight_or_noon(obj['dt_txt'])}
  end

  def midnight_or_noon(time)
    time.include?('0:00:00') || time.include?('12:00:00')
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :cities
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def new
    @city = City.new
  end

  def all_cities
    @cities = City.all
    render :index
  end

  def destroy
    @city=City.find(params[:id])
    if @city.user_id != current_user&.id
      flash[:notice] = "Thats Not Your City"
      return redirect_to root_path
    end
    @city.delete

    flash[:notice] = "City Deleted"
    redirect_to root_path
  end  

  def index
    @delete_btn= true
    @cities = user_signed_in? ? current_user.cities : City.all
  end

  def show
    @city = City.find(params[:id])
  end

  def create
    current_user.cities.create(city_params)
    redirect_to root_path
  end

  private

  def city_params
    params.require(:city).permit(:name, :state)
  end  
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def index
  end
  
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController

  def index
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
  # if code==500, then return "cloud-rain"
  # if code==505, then return "cloud-rain"
  # if code==800, then return "cloud"
  def icon_name_for_code(code)
    if code >= 200 && code < 300
      return "bolt"
    end
    if code >= 300 && code < 400
      return "cloud-rain"
    end
    if code >=500 &&code<600
      return "cloud-showers-heavy"
    end

    if code >=600 &&code<700
      return "snowflake"
    end
    if code >= 700 && code < 800
      return "smog"
    end
    if code == 800
      return "sun"
    end
    if code >= 801 && code < 900
      return "cloud"
    end
  end

  def icon_for_name(icon_name)
     "<i class='fa fa-#{icon_name}'></i>"
   end

  def icon_for_code(code)
    name = icon_name_for_code(code)
    icon_for_name(name)
  end

  def pretty_name_for_dt(dt)
    time = DateTime.strptime(dt.to_s,'%s')
    time.strftime("%A %p")
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/views/cities/index.html.erb
<% @cities.each do |city| %>
  <div class="booyah-box col-10 offset-1">
    <h1><%= link_to city.name, city_path(city) %></h1><br />
    <% if @delete_btn || true%>
      <%=link_to "delete", city_path(city), method: :delete %>
    <% end %>
    <i><%= city.state %></i><br /><br />

    <% if city.user.present? %>
      <small><%= city.user.email %></small>
    <% end %>
  </div>
<% end %>

app/views/cities/new.html.erb
<div class="booyah-box col-10 offset-1">
  <h1>Enter Your City Details</h1>
  <%= simple_form_for @city do |f| %>
    <%= f.input :name %>
    <%= f.input :state %>
    <br />
    <%= f.submit 'Create', class: 'btn btn-primary' %>
  <% end %>
</div> 

app/views/cities/show.html.erb
<br />
<h1><%= @city.name %> <%= sanitize icon_for_code(@city.current_weather["id"]) %></h1> 
<div class=row>
  <div class='col-sm-6'>
    <p>Weather Forecast
    <br />
    Current Tempature: <%= @city.current_temp["temp"] %>
    <br /> 
    Feels Like: <%= @city.current_temp["feels_like"] %>
    <br /> 
    Current Weather: <%= @city.current_weather["main"] %>
    </p>
  </div>  

  <div class='col-sm-6'>
    <% @city.filtered_five_day_forecast_list.each do |forecast| %>
      <div class='booyah-box'>
        <span><%= pretty_name_for_dt(forecast['dt']) %>:</span><%= sanitize icon_for_code(forecast['weather'][0]['id']) %>
        <%= forecast['weather'][0]['description'] %>
        <!-- <%= forecast['wind']['speed'] %> -->
          <br />
          <span>High: </span><%= forecast['main']['temp_min'] %>
          <span>Low: </span><%= forecast['main']['temp_max'] %>
      </div>
    <% end %>
  </div>  
</div>  

app/views/dashboard/index.html.erb
<div class="row">
  <div class="col-12">
    <br> 
    <h1>Weather Forecast</h1>
  </div>
</div>
    <div class="container">
      <div class="row">
        <div class="col-2 offset-1">
          <i class="fas fa-cloud"></i>
        </div>
        <div class="col-3">
          <i class="fas fa-cloud-sun-rain"></i>
        </div>
        <div class="col-1">
          <i class="fas fa-wind"></i>
        </div>
        <div class="col-4 offset-1">
          <i class="fas fa-cloud-moon-rain"></i>
        </div>
    </div>
  </div>  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Weather App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/268f3ddead.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <div id="flex-content-container">
      <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <%= link_to 'Weather App', root_path, class: 'navbar-brand' %>

        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
          <ul class="navbar-nav mr-auto mt-2 mt-md-0">
            <li class="nav-item active">
            </li>
            <li class="nav-item">
              <%= link_to 'Home', cities_path, class: 'nav-link' %>

            </li>
            <li class="nav-item">
              <%= link_to new_city_url, class: 'nav-link' do %>
              <i class="fa fa-plus-circle"></i>
              New City
              <% end %>
            </li>

          </ul>
          <ul class="navbar-nav">
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
              </li>
            <% else %>
              <li class="nav-item">
               <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
              </li>
            <% end %>
          </ul>
        </div>
      </nav>
      
      <% if notice.present? %>
        <p class="alert alert-info"><%= notice %></p>
      <% end %>
      <% if alert.present? %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>

      <div class="container">
        <%= yield %>
      </div>

    </div>

    <div id="footer">
      <div class="container">
        <br>
        <b>Kai.langrehr@gmail.com</b>
        <br/>
      </div>     
    </div> 
  </body>
</html>